name: Checkstyle2

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Checkstyle
      run: |
        sudo apt update
        sudo apt install checkstyle
        curl https://raw.githubusercontent.com/checkstyle/checkstyle/775590ffbf13fb5044adde2dc35c4b34729c211b/src/main/resources/google_checks.xml -o google_checks.xml
    - name: Run Checkstyle
      run: |
        checkstyle -v
        checkstyle . -c google_checks.xml
