name: Checkstyle

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Install Checkstyle
      run: |
        ./gradlew checkstyleMain
        ./gradlew checkstyleTest
