name: Javadocs

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate Javadocs
        run: |
          ./gradlew javadoc
          rm -r docs/javadoc
          mv core/build/docs/javadoc docs/javadoc

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "Javadocs generated"
          git push

