name: Testing

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  testing:
    runs-on: ubuntu-latest
    name: Testing
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Checkstyle
      run: |
        ./gradlew checkstyleMain
        ./gradlew checkstyleTest

    - name: Test the project with JUnit
      run: ./gradlew test
